FROM golang:latest as build-stage
WORKDIR /app
COPY hello-world.go .
COPY go.* ./
RUN go mod download
RUN go build -o hello-world .


# starting second stage
FROM alpine:latest

# copy the binary from the `build-stage`
COPY --from=build-stage /app/hello-world /bin

CMD hello-world